package com.shuyu.gsyvideoplayer;
import android.os.*;
import com.shuyu.gsyvideoplayer.listener.GSYMediaPlayerListener;
import com.shuyu.gsyvideoplayer.player.*;
import com.shuyu.gsyvideoplayer.utils.GSYVideoType;
import tv.danmaku.ijk.media.player.*;
import java.util.*;
import java.io.*;

public class SessionLifecycleTest {
 static class Listener implements GSYMediaPlayerListener {
  List<String> events=new ArrayList<>(); public void onPrepared(){events.add("prepared");} public void onAutoCompletion(){events.add("completion");} public void onCompletion(){}
  public void onBufferingUpdate(int p){events.add("buffer:"+p);} public void onSeekComplete(){events.add("seek");} public void onError(int w,int e){events.add("error:"+w);} public void onInfo(int w,int e){events.add("info:"+w);} public void onVideoSizeChanged(){events.add("size");}
  public void onBackFullscreen(){} public void onVideoPause(){} public void onVideoResume(){} public void onVideoResume(boolean s){}
 }
 static class Manager extends GSYVideoBaseManager {
  final Looper media=new Looper(); final List<IjkPlayerManager> players=new ArrayList<>(); boolean failNext;
  Manager(){mLooper=media;init();setTimeOut(8000,true);}
  protected IPlayerManager getPlayManager(){IjkPlayerManager p=new IjkPlayerManager();p.mp.failPrepare=failNext;failNext=false;players.add(p);return p;}
  void prepare(String url){super.prepare(url,null,false,1,false,null);}
  IjkPlayerManager current(){return (IjkPlayerManager)getPlayer();}
 }
 static class Fixture {Manager m=new Manager(); Listener a=new Listener(),b=new Listener(); Fixture(){m.setListener(a);m.prepare("rtsp://192.168.1.10:8554/live");m.media.drain();} void switchRequest(){m.setListener(b);m.prepare("rtsp://192.168.1.10:9554/live");} void switchNow(){switchRequest();m.media.drain();} }
 static void eq(Object a,Object b){if(!Objects.equals(a,b))throw new AssertionError("expected "+b+", got "+a);}
 static void empty(Listener l){eq(l.events,Collections.emptyList());}
 interface Callback{void send(Manager m,IjkMediaPlayer p);}
 static final LinkedHashMap<String,Callback> callbacks=new LinkedHashMap<>();
 static { callbacks.put("prepared",(m,p)->m.onPrepared(p));callbacks.put("completion",(m,p)->m.onCompletion(p));callbacks.put("buffer",(m,p)->m.onBufferingUpdate(p,73));callbacks.put("seek",(m,p)->m.onSeekComplete(p));callbacks.put("error",(m,p)->m.onError(p,99,0));callbacks.put("info-start",(m,p)->m.onInfo(p,701,0));callbacks.put("info-end",(m,p)->m.onInfo(p,702,0));callbacks.put("size",(m,p)->m.onVideoSizeChanged(p,1920,1080,1,1)); }
 static void oldTimer(){Fixture f=new Fixture();Looper.advance(6000);f.switchNow();Looper.advance(8000);empty(f.b);Looper.advance(14000);eq(f.b.events,Arrays.asList("error:-192"));}
 static void rearm(){Fixture f=new Fixture();Looper.advance(1000);f.m.onInfo(f.m.current().mp,701,0);Looper.getMainLooper().drain();Looper.advance(2000);f.m.onInfo(f.m.current().mp,701,0);Looper.getMainLooper().drain();f.a.events.clear();Looper.advance(9000);empty(f.a);Looper.advance(10000);eq(f.a.events,Arrays.asList("error:-192"));}
 static void disabled(){Fixture f=new Fixture();f.m.setTimeOut(8000,false);Looper.advance(8000);empty(f.a);}
 static void queued(Callback c,boolean dispatchBeforePrepare){Fixture f=new Fixture();c.send(f.m,f.m.current().mp);f.switchRequest();if(dispatchBeforePrepare)Looper.getMainLooper().drain();f.m.media.drain();Looper.getMainLooper().drain();empty(f.b);Looper.advance(8000);eq(f.b.events,Arrays.asList("error:-192"));}
 static void late(Callback c){Fixture f=new Fixture();IjkMediaPlayer old=f.m.current().mp;f.switchNow();c.send(f.m,old);Looper.getMainLooper().drain();empty(f.b);eq(f.m.getCurrentVideoWidth(),0);Looper.advance(8000);eq(f.b.events,Arrays.asList("error:-192"));}
 static void release(Callback c){Fixture f=new Fixture();c.send(f.m,f.m.current().mp);f.m.releaseMediaPlayer();Looper.getMainLooper().drain();f.m.media.drain();Looper.advance(8000);empty(f.a);}
 static void prepareError(){Manager m=new Manager();Listener a=new Listener(),b=new Listener();m.setListener(a);m.failNext=true;m.prepare("rtsp://192.168.1.10:8554/live");m.media.drain();m.setListener(b);m.prepare("rtsp://192.168.1.10:9554/live");m.media.drain();Looper.getMainLooper().drain();empty(b);Looper.advance(8000);eq(b.events,Arrays.asList("error:-192"));}
 static void fallbackSwitch(){GSYVideoType.smart=true;Fixture f=new Fixture();f.m.onError(f.m.current().mp,-1010,0);f.switchNow();Looper.getMainLooper().drain();eq(f.m.players.size(),2);eq(f.m.current().model.getUrl(),"rtsp://192.168.1.10:9554/live");empty(f.b);}
 static void fallbackRelease(){GSYVideoType.smart=true;Fixture f=new Fixture();f.m.onError(f.m.current().mp,-1010,0);f.m.releaseMediaPlayer();f.m.media.drain();eq(f.m.players.size(),1);Looper.advance(8000);empty(f.a);}
 static void fallbackOldPrepared(){GSYVideoType.smart=true;Fixture f=new Fixture();IjkMediaPlayer old=f.m.current().mp;f.m.onError(old,-1010,0);f.m.media.drain();IjkPlayerManager replacement=f.m.current();f.m.onPrepared(old);eq(replacement.starts,0);f.m.onPrepared(replacement.mp);eq(replacement.starts,1);eq(replacement.seek,1234L);Looper.getMainLooper().drain();eq(f.a.events,Arrays.asList("prepared"));}
 static void lateUnsupported(){GSYVideoType.smart=true;Fixture f=new Fixture();IjkMediaPlayer old=f.m.current().mp;f.switchNow();f.m.onError(old,-1010,0);f.m.media.drain();eq(f.m.players.size(),2);eq(f.m.current().model.isMediaCodecDisabled(),false);}
 static void currentCallbacks(){Fixture f=new Fixture();f.m.onPrepared(f.m.current().mp);Looper.getMainLooper().drain();eq(f.a.events,Arrays.asList("prepared"));Looper.advance(8000);eq(f.a.events,Arrays.asList("prepared"));f.a.events.clear();for(Callback c:callbacks.values())c.send(f.m,f.m.current().mp);Looper.getMainLooper().drain();eq(f.a.events,Arrays.asList("prepared","completion","buffer:73","seek","error:99","info:701","info:702","size"));eq(f.m.getCurrentVideoWidth(),1920);}
 static void listenerTransfer(){Fixture f=new Fixture();f.m.onPrepared(f.m.current().mp);f.m.setListener(f.b);Looper.getMainLooper().drain();empty(f.a);eq(f.b.events,Arrays.asList("prepared"));}
 static void inputStream(){Manager m=new Manager();Listener l=new Listener();m.setListener(l);m.prepare(new BufferedInputStream(new ByteArrayInputStream(new byte[]{1})),null,false,1,false,null);m.media.drain();m.onPrepared(m.current().mp);Looper.getMainLooper().drain();eq(l.events,Arrays.asList("prepared"));}
 static void queuedReleaseThenPrepare(){Fixture f=new Fixture();IjkPlayerManager a=f.m.current();f.m.prepare("rtsp://192.168.1.10:8555/live");f.m.releaseMediaPlayer();f.switchRequest();f.m.media.drain();eq(f.m.current().model.getUrl(),"rtsp://192.168.1.10:9554/live");eq(f.m.current().releases,0);if(a.releases<1)throw new AssertionError("old player not released");f.m.onPrepared(f.m.current().mp);Looper.getMainLooper().drain();eq(f.b.events,Arrays.asList("prepared"));Looper.advance(8000);eq(f.b.events,Arrays.asList("prepared"));}
 static void currentPrepareError(){Manager m=new Manager();Listener l=new Listener();m.setListener(l);m.failNext=true;m.prepare("rtsp://192.168.1.10:8554/live");m.media.drain();Looper.getMainLooper().drain();eq(l.events,Arrays.asList("error:1"));Looper.advance(8000);eq(l.events,Arrays.asList("error:1"));}
 static void fallbackPendingOldPrepared(){GSYVideoType.smart=true;Fixture f=new Fixture();IjkPlayerManager old=f.m.current();f.m.onError(old.mp,-1010,0);f.m.onPrepared(old.mp);eq(old.starts,0);Looper.getMainLooper().drain();empty(f.a);f.m.media.drain();IjkPlayerManager replacement=f.m.current();f.m.onPrepared(replacement.mp);eq(replacement.starts,1);eq(replacement.seek,1234L);Looper.getMainLooper().drain();eq(f.a.events,Arrays.asList("prepared"));}
 static void obsoleteDequeuedTimer(){Fixture f=new Fixture();try {java.lang.reflect.Field timer=GSYVideoBaseManager.class.getDeclaredField("mTimeOutRunnable");timer.setAccessible(true);Runnable old=(Runnable)timer.get(f.m);f.switchNow();old.run();empty(f.b);}catch(ReflectiveOperationException e){throw new AssertionError(e);}}
 static void rapidPortSwitches(){Fixture f=new Fixture();for(int i=1;i<=100;i++){Looper.advance(i*10);f.m.prepare("rtsp://192.168.1.10:"+(8554+i%3)+"/live");f.m.media.drain();}Looper.advance(8999);empty(f.a);Looper.advance(9000);eq(f.a.events,Arrays.asList("error:-192"));}
 public static void main(String[] args){LinkedHashMap<String,Runnable> tests=new LinkedHashMap<>();tests.put("same-IP-port-switch-old-timer",SessionLifecycleTest::oldTimer);tests.put("buffer-start-cancel-before-rearm",SessionLifecycleTest::rearm);tests.put("disable-timeout-cancels-armed",SessionLifecycleTest::disabled);for(Map.Entry<String,Callback> e:callbacks.entrySet()){tests.put("queued-before-new-init-"+e.getKey(),()->queued(e.getValue(),true));tests.put("queued-after-new-init-"+e.getKey(),()->queued(e.getValue(),false));tests.put("late-old-player-"+e.getKey(),()->late(e.getValue()));tests.put("release-queued-"+e.getKey(),()->release(e.getValue()));}tests.put("queued-prepare-error",SessionLifecycleTest::prepareError);tests.put("queued-fallback-then-switch",SessionLifecycleTest::fallbackSwitch);tests.put("queued-fallback-then-release",SessionLifecycleTest::fallbackRelease);tests.put("fallback-old-prepared-does-not-resume-new-player",SessionLifecycleTest::fallbackOldPrepared);tests.put("old-unsupported-does-not-fallback-new-player",SessionLifecycleTest::lateUnsupported);tests.put("current-callbacks-still-delivered",SessionLifecycleTest::currentCallbacks);tests.put("same-session-fullscreen-listener-transfer",SessionLifecycleTest::listenerTransfer);tests.put("input-stream-prepare-still-delivered",SessionLifecycleTest::inputStream);tests.put("prepare-release-prepare-queue-order",SessionLifecycleTest::queuedReleaseThenPrepare);tests.put("current-prepare-failure-reports-once",SessionLifecycleTest::currentPrepareError);tests.put("fallback-pending-old-prepared",SessionLifecycleTest::fallbackPendingOldPrepared);tests.put("already-dequeued-old-watchdog-is-inert",SessionLifecycleTest::obsoleteDequeuedTimer);tests.put("rapid-port-revisit-rearms-full-deadline",SessionLifecycleTest::rapidPortSwitches);int failed=0;for(Map.Entry<String,Runnable> e:tests.entrySet()){Looper.reset();GSYVideoType.smart=false;try{e.getValue().run();System.out.println("PASS "+e.getKey());}catch(Throwable t){failed++;System.out.println("FAIL "+e.getKey()+": "+t);}}System.out.println("RESULT tests="+tests.size()+" passed="+(tests.size()-failed)+" failed="+failed);if(failed!=0)System.exit(1);}
}
